/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tallerreto.tallerinformatica;

/**
 *La VentanaInventario es la gestion de Materiales
 * Permite ver-Buscar-Editar-Eliminar o Volver
 * Si estas con la Cuenta Profesor no podras usar las opciones de Modificación
 * @author Sergio Iturbe Sánchez
 */
public class VentanaInventario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInventario
     */
   private Modelo.Usuario usuario;
/**
 * Constructor de la VentanaInventario, Se inician los Componentes, carga la tabla... y si es Profesor se bloquean las opciones de modificacion
 * @param usuario 
 * @author Sergio Iturbe Sánchez
 */
public VentanaInventario(Modelo.Usuario usuario) {
    this.usuario = usuario;
    initComponents();
    cargarTabla();
    
    // Si es profesor, ocultar botones de modificación
    if (usuario.getRol().equals("profesor")) {
        btnAñadir.setVisible(false);
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
    }
}
/**
 * Aqui se obtiene de la Base de Datos y se rellena en las columnas los datos
 * @author Sergio Iturbe Sánchez
 */
private void cargarTabla() {
    String[] columnas = {"ID", "Nombre", "Categoría", "Ubicación", "Cantidad", "Estado"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);
    
    Dao.MaterialDAO dao = new Dao.MaterialDAO();
    java.util.List<Modelo.Material> materiales = dao.obtenerMateriales();
    
    for (Modelo.Material m : materiales) {
        Object[] fila = {m.getId(), m.getNombre(), m.getCategoria(), m.getUbicacion(), m.getCantidad(), m.getEstado()};
        modelo.addRow(fila);
    }
    tablaInventario.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInventario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 413;
        gridBagConstraints.ipady = 478;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 148, 0, 136);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 14, 0, 0);
        getContentPane().add(txtBuscar, gridBagConstraints);

        jLabel1.setText("Buscar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 178, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 18, 0, 0);
        getContentPane().add(btnBuscar, gridBagConstraints);

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 148, 10, 0);
        getContentPane().add(btnAñadir, gridBagConstraints);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 53, 10, 0);
        getContentPane().add(btnEditar, gridBagConstraints);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 10, 0);
        getContentPane().add(btnEliminar, gridBagConstraints);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 10, 0);
        getContentPane().add(btnVolver, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Texto de "Buscar" que acompaña al Buscador del Inventario
 * @param evt
 * @author Sergio Iturbe Sánchez
 */
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed
/**
 * Aqui se filtra el Inventario segun palabras clave del Buscador por ejemplo "Router"
 * @param evt 
 * @author Sergio Iturbe Sánchez
 */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String busqueda = txtBuscar.getText().toLowerCase();
javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaInventario.getModel();
modelo.setRowCount(0);

Dao.MaterialDAO dao = new Dao.MaterialDAO();
java.util.List<Modelo.Material> materiales = dao.obtenerMateriales();

for (Modelo.Material m : materiales) {
    if (m.getNombre().toLowerCase().contains(busqueda) ||
        m.getCategoria().toLowerCase().contains(busqueda)) {
        Object[] fila = {m.getNombre(), m.getCategoria(), m.getUbicacion(), m.getCantidad(), m.getEstado()};
        modelo.addRow(fila);
    }
}
    }//GEN-LAST:event_btnBuscarActionPerformed
/**
 * Este Boton permite al Admin añadir un nuevo material al Inventario
 * Se presentan varias opciones como Descripcion-Cantidad-Estados-Su ID de categoria y Ubicacion...
 * @param evt 
 * @author Sergio Iturbe Sánchez
 */
    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre del material:");
if (nombre == null || nombre.isEmpty()) return;
String descripcion = javax.swing.JOptionPane.showInputDialog(this, "Descripción:");
String cantidadStr = javax.swing.JOptionPane.showInputDialog(this, "Cantidad:");
String estado = javax.swing.JOptionPane.showInputDialog(this, "Estado (disponible/prestado/reparacion/Baja):");
String idCatStr = javax.swing.JOptionPane.showInputDialog(this, "ID Categoría (1=Red, 2=Hardware, 3=Herramientas):");
String idUbicStr = javax.swing.JOptionPane.showInputDialog(this, "ID Ubicación (1, 2 o 3):");

try {
    int cantidad = Integer.parseInt(cantidadStr);
    int idCat = Integer.parseInt(idCatStr);
    int idUbic = Integer.parseInt(idUbicStr);
    Dao.MaterialDAO dao = new Dao.MaterialDAO();
    dao.insertar(nombre, descripcion, cantidad, estado, idCat, idUbic);
    javax.swing.JOptionPane.showMessageDialog(this, "Material añadido correctamente");
    cargarTabla();
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al añadir: " + ex.getMessage());
}
    }//GEN-LAST:event_btnAñadirActionPerformed
/**
 * Este otro boton permite Elimiar un Material del Inventario, hay que selecionar una fila, si no te muestra un aviso
 * @param evt 
 * @author Sergio Iturbe Sánchez
 */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablaInventario.getSelectedRow();
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un material de la tabla");
    return;
}
int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "¿Eliminar este material?");
if (confirm == javax.swing.JOptionPane.YES_OPTION) {
    javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) tablaInventario.getModel();
    int id = (int) modelo.getValueAt(fila, 0);
    Dao.MaterialDAO dao = new Dao.MaterialDAO();
    dao.eliminar(id);
    javax.swing.JOptionPane.showMessageDialog(this, "Material eliminado");
    cargarTabla();
}
    }//GEN-LAST:event_btnEliminarActionPerformed
/**
 * Este boton simplemente permite volver a la anterior ventana
 * @param evt 
 * @author Sergio Iturbe Sánchez
 */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
/**
 * Este boton te deja Editar un material existente en el Inventario preguntandote por las Nuevas Opciones de Modificacion
 * @param evt 
 * @author Sergio Iturbe Sánchez
 */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tablaInventario.getSelectedRow();
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un material de la tabla");
    return;
}
javax.swing.table.DefaultTableModel modelo = 
    (javax.swing.table.DefaultTableModel) tablaInventario.getModel();
int id = (int) modelo.getValueAt(fila, 0);
String nombreActual = (String) modelo.getValueAt(fila, 1);

String nuevoNombre = javax.swing.JOptionPane.showInputDialog(this, "Nuevo nombre:", nombreActual);
if (nuevoNombre == null) return;
String cantidadStr = javax.swing.JOptionPane.showInputDialog(this, "Nueva cantidad:", modelo.getValueAt(fila, 3));
String nuevoEstado = javax.swing.JOptionPane.showInputDialog(this, "Nuevo estado:", modelo.getValueAt(fila, 4));

try {
    int cantidad = Integer.parseInt(cantidadStr);
    Dao.MaterialDAO dao = new Dao.MaterialDAO();
    dao.actualizar(id, nuevoNombre, cantidad, nuevoEstado);
    javax.swing.JOptionPane.showMessageDialog(this, "Material actualizado");
    cargarTabla();
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());

    }//GEN-LAST:event_btnEditarActionPerformed
    }
    /**
     *Lanza la ventana de Login 
     * @param args the command line arguments
     * @author Sergio Iturbe Sánchez
     */
    public static  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new tallerreto.tallerinformatica.LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
